sra format
use tabs: true
0-r:Root
	1-o:asset
		2-v:type
			3-s:FluxGraphAsset
		2-o:ptr
			3-o:graph
				4-a:nodes
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:1484
								8-v:y
									9-f:1028
							7-v:callableObject
								8-s:123
							7-v:callableFunction
								8-s:123ss
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-802
								8-v:y
									9-f:372
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:1070
								8-v:y
									9-f:1300
							7-o:constant
								8-v:typeInfo
									9-s:String.String
								8-v:string
									9-s:qwe
					5-k:i
						6-o:d
							7-v:type
								8-s:ReadVariable
							7-v:name
								8-s:fff
							7-o:position
								8-v:x
									9-f:-1072
								8-v:y
									9-f:228
					5-k:i
						6-o:d
							7-v:type
								8-s:WriteVariable
							7-v:name
								8-s:www
							7-o:position
								8-v:x
									9-f:-1056
								8-v:y
									9-f:410
					5-k:i
						6-o:d
							7-v:type
								8-s:While
							7-o:position
								8-v:x
									9-f:-845
								8-v:y
									9-f:580
					5-k:i
						6-o:d
							7-v:type
								8-s:For
							7-o:position
								8-v:x
									9-f:-573
								8-v:y
									9-f:592
					5-k:i
						6-o:d
							7-v:type
								8-s:Branch
							7-o:position
								8-v:x
									9-f:2558
								8-v:y
									9-f:1284
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:1900
								8-v:y
									9-f:1028
							7-v:callableObject
								8-s:ddd
							7-v:callableFunction
								8-s:ddd
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:1054
								8-v:y
									9-f:1156
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.int32
								8-v:int
									9-i:0
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:2190
								8-v:y
									9-f:1284
							7-v:callableObject
								8-s:55
							7-v:callableFunction
								8-s:55
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:2956
								8-v:y
									9-f:1156
							7-v:callableObject
								8-s:11
							7-v:callableFunction
								8-s:11
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:2987
								8-v:y
									9-f:1423
							7-v:callableObject
								8-s:22
							7-v:callableFunction
								8-s:22
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:2206
								8-v:y
									9-f:1540
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.int32
								8-v:int
									9-i:0
					5-k:i
						6-o:d
							7-v:type
								8-s:Branch
							7-o:position
								8-v:x
									9-f:3308
								8-v:y
									9-f:1156
					5-k:i
						6-o:d
							7-v:type
								8-s:Event
							7-v:name
								8-s:Update
							7-o:position
								8-v:x
									9-f:-162
								8-v:y
									9-f:-668
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-162
								8-v:y
									9-f:-508
							7-o:constant
								8-v:typeInfo
									9-s:String.String
								8-v:string
									9-s:Hello from Flux!
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:302
								8-v:y
									9-f:-668
							7-v:callableObject
								8-s:Debug
							7-v:callableFunction
								8-s:Info
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:316
								8-v:y
									9-f:-844
							7-v:callableObject
								8-s:Component
							7-v:callableFunction
								8-s:GetGameObject
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:574
								8-v:y
									9-f:-844
							7-v:callableObject
								8-s:GameObject
							7-v:callableFunction
								8-s:GetTransform
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:860
								8-v:y
									9-f:-668
							7-v:callableObject
								8-s:Transform
							7-v:callableFunction
								8-s:RotateXYZ
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:1
								8-v:y
									9-f:-844
							7-v:callableObject
								8-s:FluxUtils
							7-v:callableFunction
								8-s:GetActiveFluxComponent
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:302
								8-v:y
									9-f:-524
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:0
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:302
								8-v:y
									9-f:-412
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:-1
				4-a:links
					5-k:i
						6-o:d
							7-v:targetNode
								8-i:8
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:9
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:2
							7-v:targetNode
								8-i:10
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:8
							7-v:targetNode
								8-i:10
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:10
							7-v:targetNode
								8-i:7
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:7
							7-v:targetNode
								8-i:11
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:7
							7-v:targetNode
								8-i:12
							7-v:sourcePin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:13
							7-v:targetNode
								8-i:7
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:11
							7-v:targetNode
								8-i:14
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:13
							7-v:targetNode
								8-i:14
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:15
							7-v:targetNode
								8-i:17
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:16
							7-v:targetNode
								8-i:17
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:18
							7-v:targetNode
								8-i:19
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:17
							7-v:targetNode
								8-i:20
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:19
							7-v:targetNode
								8-i:20
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:21
							7-v:targetNode
								8-i:18
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:23
							7-v:targetNode
								8-i:20
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:22
							7-v:targetNode
								8-i:20
							7-v:targetPin
								8-i:3
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:22
							7-v:targetNode
								8-i:20
							7-v:targetPin
								8-i:4
				4-a:variables
					5-k:item
						6-v:first
							7-s:www
						6-o:second
							7-v:typeInfo
								8-s:Arithmetic.bool
							7-v:bool
								8-b:false
					5-k:item
						6-v:first
							7-s:fff
						6-o:second
							7-v:typeInfo
								8-s:Arithmetic.double
							7-v:double
								8-d:0
