sra format
use tabs: true
0-r:Root
	1-o:asset
		2-v:type
			3-s:FluxGraphAsset
		2-o:ptr
			3-o:graph
				4-a:nodes
					5-k:i
						6-o:d
							7-v:type
								8-s:Event
							7-v:name
								8-s:Animate
							7-o:position
								8-v:x
									9-f:-82
								8-v:y
									9-f:36
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:356.999
								8-v:y
									9-f:119.35
							7-v:callableObject
								8-s:AnimationGraphNodeStateMachine
							7-v:callableFunction
								8-s:Update
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:796
								8-v:y
									9-f:132
							7-v:callableObject
								8-s:AnimationGraphNodeLinearBlend
							7-v:callableFunction
								8-s:Update
				4-a:variables
