sra format
use tabs: true
0-r:Root
	1-o:asset
		2-v:type
			3-s:FluxGraphAsset
		2-o:ptr
			3-o:graph
				4-a:nodes
					5-k:i
						6-o:d
							7-v:type
								8-s:Event
							7-v:name
								8-s:FixedUpdate
							7-o:position
								8-v:x
									9-f:-2658
								8-v:y
									9-f:2676
					5-k:i
						6-o:d
							7-v:type
								8-s:Cast
							7-v:name
								8-s:CharacterController
							7-o:position
								8-v:x
									9-f:-1712
								8-v:y
									9-f:3546
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-2324
								8-v:y
									9-f:3428
							7-v:callableObject
								8-s:FluxComponent
							7-v:callableFunction
								8-s:GetSceneObject
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-2034
								8-v:y
									9-f:3492
							7-v:callableObject
								8-s:SceneObject
							7-v:callableFunction
								8-s:GetComponent
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-2524
								8-v:y
									9-f:3520
							7-o:constant
								8-v:typeInfo
									9-s:String.String
								8-v:string
									9-s:CharacterController
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-2302
								8-v:y
									9-f:3520
							7-v:callableObject
								8-s:StringUtils
							7-v:callableFunction
								8-s:MakeAtom
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:-1172
								8-v:y
									9-f:3904
							7-v:callableObject
								8-s:CharacterController
							7-v:callableFunction
								8-s:Move
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-1442
								8-v:y
									9-f:4148
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:0.01
					5-k:i
						6-o:d
							7-v:type
								8-s:Branch
							7-o:position
								8-v:x
									9-f:3376
								8-v:y
									9-f:2736
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:2730
								8-v:y
									9-f:3360
							7-v:callableObject
								8-s:Input
							7-v:callableFunction
								8-s:GetKey
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:2500
								8-v:y
									9-f:3360
							7-o:constant
								8-v:typeInfo
									9-s:Enum.KeyCode
								8-v:enum
									9-s:W
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:3150
								8-v:y
									9-f:2602
							7-o:constant
								8-v:typeInfo
									9-s:MathVector.float(3)
								8-v:x
									9-i:0
								8-v:y
									9-i:1065353216
								8-v:z
									9-i:0
					5-k:i
						6-o:d
							7-v:type
								8-s:WriteVariable
							7-v:name
								8-s:Direction
							7-o:position
								8-v:x
									9-f:3614
								8-v:y
									9-f:2736
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:3374
								8-v:y
									9-f:2602
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:SumFVector3
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:2500
								8-v:y
									9-f:3472
							7-o:constant
								8-v:typeInfo
									9-s:Enum.KeyCode
								8-v:enum
									9-s:S
					5-k:i
						6-o:d
							7-v:type
								8-s:WriteVariable
							7-v:name
								8-s:Direction
							7-o:position
								8-v:x
									9-f:3614
								8-v:y
									9-f:3046
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:2730
								8-v:y
									9-f:3472
							7-v:callableObject
								8-s:Input
							7-v:callableFunction
								8-s:GetKey
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:3374
								8-v:y
									9-f:2912
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:SumFVector3
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:3147
								8-v:y
									9-f:2911
							7-o:constant
								8-v:typeInfo
									9-s:MathVector.float(3)
								8-v:x
									9-i:0
								8-v:y
									9-i:3212836864
								8-v:z
									9-i:0
					5-k:i
						6-o:d
							7-v:type
								8-s:ReadVariable
							7-v:name
								8-s:Direction
							7-o:position
								8-v:x
									9-f:2622
								8-v:y
									9-f:2628
					5-k:i
						6-o:d
							7-v:type
								8-s:Branch
							7-o:position
								8-v:x
									9-f:3376
								8-v:y
									9-f:3046
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:3374
								8-v:y
									9-f:3242
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:SumFVector3
					5-k:i
						6-o:d
							7-v:type
								8-s:Branch
							7-o:position
								8-v:x
									9-f:3376
								8-v:y
									9-f:3376
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:3147
								8-v:y
									9-f:3241
							7-o:constant
								8-v:typeInfo
									9-s:MathVector.float(3)
								8-v:x
									9-i:3212836864
								8-v:y
									9-i:0
								8-v:z
									9-i:0
					5-k:i
						6-o:d
							7-v:type
								8-s:WriteVariable
							7-v:name
								8-s:Direction
							7-o:position
								8-v:x
									9-f:3614
								8-v:y
									9-f:3376
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:2728
								8-v:y
									9-f:3595
							7-v:callableObject
								8-s:Input
							7-v:callableFunction
								8-s:GetKey
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:2498
								8-v:y
									9-f:3595
							7-o:constant
								8-v:typeInfo
									9-s:Enum.KeyCode
								8-v:enum
									9-s:A
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:3152
								8-v:y
									9-f:3551
							7-o:constant
								8-v:typeInfo
									9-s:MathVector.float(3)
								8-v:x
									9-i:1065353216
								8-v:y
									9-i:0
								8-v:z
									9-i:0
					5-k:i
						6-o:d
							7-v:type
								8-s:Branch
							7-o:position
								8-v:x
									9-f:3381
								8-v:y
									9-f:3686
					5-k:i
						6-o:d
							7-v:type
								8-s:WriteVariable
							7-v:name
								8-s:Direction
							7-o:position
								8-v:x
									9-f:3619
								8-v:y
									9-f:3686
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:3379
								8-v:y
									9-f:3552
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:SumFVector3
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:2500
								8-v:y
									9-f:3712
							7-o:constant
								8-v:typeInfo
									9-s:Enum.KeyCode
								8-v:enum
									9-s:D
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:2730
								8-v:y
									9-f:3712
							7-v:callableObject
								8-s:Input
							7-v:callableFunction
								8-s:GetKey
					5-k:i
						6-o:d
							7-v:type
								8-s:WriteVariable
							7-v:name
								8-s:Direction
							7-o:position
								8-v:x
									9-f:-1554
								8-v:y
									9-f:2634
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-1778
								8-v:y
									9-f:2612
							7-o:constant
								8-v:typeInfo
									9-s:MathVector.float(3)
								8-v:x
									9-i:0
								8-v:y
									9-i:0
								8-v:z
									9-i:0
					5-k:i
						6-o:d
							7-v:type
								8-s:Sequence
							7-o:position
								8-v:x
									9-f:-2146
								8-v:y
									9-f:2676
					5-k:i
						6-o:d
							7-v:type
								8-s:ReadVariable
							7-v:name
								8-s:Direction
							7-o:position
								8-v:x
									9-f:-2994
								8-v:y
									9-f:3940
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-8301
								8-v:y
									9-f:3905
							7-v:callableObject
								8-s:Input
							7-v:callableFunction
								8-s:GetMouseDrag
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-2757
								8-v:y
									9-f:3914
							7-v:callableObject
								8-s:Transform
							7-v:callableFunction
								8-s:TransformDirection
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-2996
								8-v:y
									9-f:3844
							7-v:callableObject
								8-s:GameObject
							7-v:callableFunction
								8-s:GetTransform
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-3237
								8-v:y
									9-f:3840
							7-v:callableObject
								8-s:FluxComponent
							7-v:callableFunction
								8-s:GetGameObject
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:-7378
								8-v:y
									9-f:4160
							7-v:callableObject
								8-s:Transform
							7-v:callableFunction
								8-s:RotateXYZ
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-7872
								8-v:y
									9-f:3906
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:GetFVector2X
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-7614
								8-v:y
									9-f:4354
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:0
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-7618
								8-v:y
									9-f:3972
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:MultiplyFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-7872
								8-v:y
									9-f:3998
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:0.1
					5-k:i
						6-o:d
							7-v:type
								8-s:Sequence
							7-o:position
								8-v:x
									9-f:2620
								8-v:y
									9-f:2732
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-2722
								8-v:y
									9-f:4244
							7-v:callableObject
								8-s:Time
							7-v:callableFunction
								8-s:FixedDeltaTime
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-2498
								8-v:y
									9-f:3946
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:Normalize
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-2223
								8-v:y
									9-f:3946
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:MultiplyFVector3Float
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-2484
								8-v:y
									9-f:4084
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:MultiplyFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-1588
								8-v:y
									9-f:3956
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:MakeFVector3
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-1892
								8-v:y
									9-f:3956
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:GetFVector3X
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-1892
								8-v:y
									9-f:4036
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:GetFVector3Z
					5-k:i
						6-o:d
							7-v:type
								8-s:ReadVariable
							7-v:name
								8-s:VerticalVelocity
							7-o:position
								8-v:x
									9-f:-2082
								8-v:y
									9-f:3780
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-1443
								8-v:y
									9-f:4244
							7-o:constant
								8-v:typeInfo
									9-s:Enum.CharacterControllerCollisionFlags
								8-v:enum
									9-s:Down
					5-k:i
						6-o:d
							7-v:type
								8-s:Branch
							7-o:position
								8-v:x
									9-f:-658
								8-v:y
									9-f:3908
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-914
								8-v:y
									9-f:3988
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:BitAnd
					5-k:i
						6-o:d
							7-v:type
								8-s:WriteVariable
							7-v:name
								8-s:VerticalVelocity
							7-o:position
								8-v:x
									9-f:-116
								8-v:y
									9-f:3908
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-354
								8-v:y
									9-f:3844
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:0
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-898
								8-v:y
									9-f:4250
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:9.81
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-418
								8-v:y
									9-f:4234
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:SubtractFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-660
								8-v:y
									9-f:4314
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:MultiplyFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:ReadVariable
							7-v:name
								8-s:VerticalVelocity
							7-o:position
								8-v:x
									9-f:-658
								8-v:y
									9-f:4218
					5-k:i
						6-o:d
							7-v:type
								8-s:WriteVariable
							7-v:name
								8-s:VerticalVelocity
							7-o:position
								8-v:x
									9-f:-114
								8-v:y
									9-f:4042
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-1844
								8-v:y
									9-f:3780
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:MultiplyFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-3156
								8-v:y
									9-f:4084
							7-v:callableObject
								8-s:FluxComponent
							7-v:callableFunction
								8-s:GetVariable
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-3426
								8-v:y
									9-f:4260
							7-o:constant
								8-v:typeInfo
									9-s:String.StringAtom
								8-v:atom
									9-s:WalkSpeed
					5-k:i
						6-o:d
							7-v:type
								8-s:Cast
							7-v:name
								8-s:GameObject
							7-o:position
								8-v:x
									9-f:-7856
								8-v:y
									9-f:4162
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-8352
								8-v:y
									9-f:4290
							7-v:callableObject
								8-s:FluxComponent
							7-v:callableFunction
								8-s:GetVariable
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-8590
								8-v:y
									9-f:4386
							7-o:constant
								8-v:typeInfo
									9-s:String.StringAtom
								8-v:atom
									9-s:Camera
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-8110
								8-v:y
									9-f:4290
							7-v:callableObject
								8-s:EntityRefDynamic
							7-v:callableFunction
								8-s:GetEntity
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-8048
								8-v:y
									9-f:4606
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:GetFVector2Y
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:-6896
								8-v:y
									9-f:4162
							7-v:callableObject
								8-s:Transform
							7-v:callableFunction
								8-s:SetRotationXYZ
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-7614
								8-v:y
									9-f:4274
							7-v:callableObject
								8-s:GameObject
							7-v:callableFunction
								8-s:GetTransform
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-7806
								8-v:y
									9-f:4610
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:MultiplyFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-8046
								8-v:y
									9-f:4722
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:0.1
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-8046
								8-v:y
									9-f:4882
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:75
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-7296
								8-v:y
									9-f:4770
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:ClampFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-7742
								8-v:y
									9-f:4740
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:MultiplyFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-8046
								8-v:y
									9-f:4802
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:-1
					5-k:i
						6-o:d
							7-v:type
								8-s:WriteVariable
							7-v:name
								8-s:CameraPitch
							7-o:position
								8-v:x
									9-f:-7136
								8-v:y
									9-f:4160
					5-k:i
						6-o:d
							7-v:type
								8-s:ReadVariable
							7-v:name
								8-s:CameraPitch
							7-o:position
								8-v:x
									9-f:-7806
								8-v:y
									9-f:4498
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-7518
								8-v:y
									9-f:4674
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:SumFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-3450
								8-v:y
									9-f:4516
							7-o:constant
								8-v:typeInfo
									9-s:Enum.KeyCode
								8-v:enum
									9-s:LShift
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-3202
								8-v:y
									9-f:4516
							7-v:callableObject
								8-s:Input
							7-v:callableFunction
								8-s:GetKey
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-3426
								8-v:y
									9-f:4180
							7-o:constant
								8-v:typeInfo
									9-s:String.StringAtom
								8-v:atom
									9-s:RunSpeed
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-3156
								8-v:y
									9-f:4196
							7-v:callableObject
								8-s:FluxComponent
							7-v:callableFunction
								8-s:GetVariable
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-2818
								8-v:y
									9-f:4084
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:SwitchFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-340
								8-v:y
									9-f:4766
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:Length
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-52
								8-v:y
									9-f:4766
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:IsFloatGreater
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-338
								8-v:y
									9-f:4862
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:0
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:300
								8-v:y
									9-f:4596
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:BoolAnd
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-566
								8-v:y
									9-f:3439
							7-o:constant
								8-v:typeInfo
									9-s:String.StringAtom
								8-v:atom
									9-s:Animator
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-338
								8-v:y
									9-f:3412
							7-v:callableObject
								8-s:FluxComponent
							7-v:callableFunction
								8-s:GetVariable
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:942
								8-v:y
									9-f:3910
							7-v:callableObject
								8-s:Animator
							7-v:callableFunction
								8-s:SetBool
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:670
								8-v:y
									9-f:4084
							7-o:constant
								8-v:typeInfo
									9-s:String.StringAtom
								8-v:atom
									9-s:Run
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:1214
								8-v:y
									9-f:3910
							7-v:callableObject
								8-s:Animator
							7-v:callableFunction
								8-s:SetBool
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:974
								8-v:y
									9-f:4084
							7-o:constant
								8-v:typeInfo
									9-s:String.StringAtom
								8-v:atom
									9-s:Walk
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:636
								8-v:y
									9-f:4750
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:BoolAnd
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:204
								8-v:y
									9-f:4894
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:BoolNot
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-114
								8-v:y
									9-f:3422
							7-v:callableObject
								8-s:EntityRefDynamic
							7-v:callableFunction
								8-s:GetEntity
					5-k:i
						6-o:d
							7-v:type
								8-s:Cast
							7-v:name
								8-s:Animator
							7-o:position
								8-v:x
									9-f:206
								8-v:y
									9-f:3546
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-8621
								8-v:y
									9-f:4290
							7-v:callableObject
								8-s:FluxUtils
							7-v:callableFunction
								8-s:GetActiveFluxComponent
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-2575
								8-v:y
									9-f:3428
							7-v:callableObject
								8-s:FluxUtils
							7-v:callableFunction
								8-s:GetActiveFluxComponent
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-593
								8-v:y
									9-f:3348
							7-v:callableObject
								8-s:FluxUtils
							7-v:callableFunction
								8-s:GetActiveFluxComponent
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-3491
								8-v:y
									9-f:3844
							7-v:callableObject
								8-s:FluxUtils
							7-v:callableFunction
								8-s:GetActiveFluxComponent
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-3441
								8-v:y
									9-f:4084
							7-v:callableObject
								8-s:FluxUtils
							7-v:callableFunction
								8-s:GetActiveFluxComponent
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-8129
								8-v:y
									9-f:3812
							7-v:callableObject
								8-s:FluxUtils
							7-v:callableFunction
								8-s:GetActiveFluxComponent
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-7875
								8-v:y
									9-f:3808
							7-v:callableObject
								8-s:FluxComponent
							7-v:callableFunction
								8-s:GetGameObject
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-7634
								8-v:y
									9-f:3812
							7-v:callableObject
								8-s:GameObject
							7-v:callableFunction
								8-s:GetTransform
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-9637
								8-v:y
									9-f:2154
							7-v:callableObject
								8-s:FluxUtils
							7-v:callableFunction
								8-s:GetActiveFluxComponent
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-9158
								8-v:y
									9-f:2218
							7-v:callableObject
								8-s:EntityRefDynamic
							7-v:callableFunction
								8-s:GetEntity
					5-k:i
						6-o:d
							7-v:type
								8-s:Cast
							7-v:name
								8-s:GameObject
							7-o:position
								8-v:x
									9-f:-8899
								8-v:y
									9-f:2168
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-9382
								8-v:y
									9-f:2218
							7-v:callableObject
								8-s:FluxComponent
							7-v:callableFunction
								8-s:GetVariable
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-9610
								8-v:y
									9-f:2245
							7-o:constant
								8-v:typeInfo
									9-s:String.StringAtom
								8-v:atom
									9-s:HeadModel
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-9138
								8-v:y
									9-f:2436
							7-v:callableObject
								8-s:Input
							7-v:callableFunction
								8-s:IsPlayMode
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:-8612
								8-v:y
									9-f:2170
							7-v:callableObject
								8-s:SceneObject
							7-v:callableFunction
								8-s:SetEnabled
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-8898
								8-v:y
									9-f:2308
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:BoolNot
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-102
								8-v:y
									9-f:4958
							7-v:callableObject
								8-s:Input
							7-v:callableFunction
								8-s:GetKey
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-350
								8-v:y
									9-f:4958
							7-o:constant
								8-v:typeInfo
									9-s:Enum.KeyCode
								8-v:enum
									9-s:LShift
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-898
								8-v:y
									9-f:4340
							7-v:callableObject
								8-s:Time
							7-v:callableFunction
								8-s:FixedDeltaTime
					5-k:i
						6-o:d
							7-v:type
								8-s:Event
							7-v:name
								8-s:Update
							7-o:position
								8-v:x
									9-f:-9252
								8-v:y
									9-f:1802
					5-k:i
						6-o:d
							7-v:type
								8-s:Sequence
							7-o:position
								8-v:x
									9-f:-8098
								8-v:y
									9-f:2170
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:-6576
								8-v:y
									9-f:2078
							7-v:callableObject
								8-s:CursorLock
							7-v:callableFunction
								8-s:Lock
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-7072
								8-v:y
									9-f:2232
							7-o:constant
								8-v:typeInfo
									9-s:Enum.CursorLockMode
								8-v:enum
									9-s:PlayMode
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:-6827
								8-v:y
									9-f:2168
							7-v:callableObject
								8-s:CursorLock
							7-v:callableFunction
								8-s:SetLockMode
					5-k:i
						6-o:d
							7-v:type
								8-s:ReadVariable
							7-v:name
								8-s:CursorLock
							7-o:position
								8-v:x
									9-f:-7088
								8-v:y
									9-f:2104
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-2082
								8-v:y
									9-f:3860
							7-v:callableObject
								8-s:Time
							7-v:callableFunction
								8-s:FixedDeltaTime
					5-k:i
						6-o:d
							7-v:type
								8-s:WriteVariable
							7-v:name
								8-s:BodyYawTarget
							7-o:position
								8-v:x
									9-f:4268
								8-v:y
									9-f:3684
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:3422
								8-v:y
									9-f:4132
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:MultiplyFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:3117
								8-v:y
									9-f:4132
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:SwitchFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:2110
								8-v:y
									9-f:4132
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:45
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:2110
								8-v:y
									9-f:4212
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:90
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:3118
								8-v:y
									9-f:4318
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:SwitchFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:2814
								8-v:y
									9-f:4398
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:1
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:2558
								8-v:y
									9-f:4324
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:-1
					5-k:i
						6-o:d
							7-v:type
								8-s:Branch
							7-o:position
								8-v:x
									9-f:3964
								8-v:y
									9-f:3684
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:3388
								8-v:y
									9-f:3812
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:BoolOr
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:2492
								8-v:y
									9-f:4132
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:SwitchFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:2796
								8-v:y
									9-f:4202
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:MultiplyFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:WriteVariable
							7-v:name
								8-s:BodyYawTarget
							7-o:position
								8-v:x
									9-f:4268
								8-v:y
									9-f:3834
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:3998
								8-v:y
									9-f:3956
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:0
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-6836
								8-v:y
									9-f:2612
							7-v:callableObject
								8-s:EntityRefDynamic
							7-v:callableFunction
								8-s:GetEntity
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-7345
								8-v:y
									9-f:2612
							7-v:callableObject
								8-s:FluxUtils
							7-v:callableFunction
								8-s:GetActiveFluxComponent
					5-k:i
						6-o:d
							7-v:type
								8-s:Cast
							7-v:name
								8-s:GameObject
							7-o:position
								8-v:x
									9-f:-6598
								8-v:y
									9-f:2538
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-7076
								8-v:y
									9-f:2612
							7-v:callableObject
								8-s:FluxComponent
							7-v:callableFunction
								8-s:GetVariable
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-7314
								8-v:y
									9-f:2692
							7-o:constant
								8-v:typeInfo
									9-s:String.StringAtom
								8-v:atom
									9-s:Body
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-6354
								8-v:y
									9-f:2616
							7-v:callableObject
								8-s:GameObject
							7-v:callableFunction
								8-s:GetTransform
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-6402
								8-v:y
									9-f:2980
							7-v:callableObject
								8-s:Time
							7-v:callableFunction
								8-s:DeltaTime
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-6098
								8-v:y
									9-f:2696
							7-v:callableObject
								8-s:Transform
							7-v:callableFunction
								8-s:GetQuaternion
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-5828
								8-v:y
									9-f:2698
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:SlerpQuaternion
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-6149
								8-v:y
									9-f:2782
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:QuaternionFromEulerAngles
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-6400
								8-v:y
									9-f:2808
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:0
					5-k:i
						6-o:d
							7-v:type
								8-s:ReadVariable
							7-v:name
								8-s:BodyYawTarget
							7-o:position
								8-v:x
									9-f:-6400
								8-v:y
									9-f:2888
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:-5586
								8-v:y
									9-f:2538
							7-v:callableObject
								8-s:Transform
							7-v:callableFunction
								8-s:SetQuaternion
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-6082
								8-v:y
									9-f:2922
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:MultiplyFloat
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-6402
								8-v:y
									9-f:3060
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:5
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:2302
								8-v:y
									9-f:3914
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:BoolOr
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-6360
								8-v:y
									9-f:4691
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:QuaternionFromEulerAngles
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-6611
								8-v:y
									9-f:4717
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:0
					5-k:i
						6-o:d
							7-v:type
								8-s:ReadVariable
							7-v:name
								8-s:BodyYawTarget
							7-o:position
								8-v:x
									9-f:-6611
								8-v:y
									9-f:4797
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-6066
								8-v:y
									9-f:4692
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:InverseQuaternion
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:-5940
								8-v:y
									9-f:4160
							7-v:callableObject
								8-s:Transform
							7-v:callableFunction
								8-s:Follow
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-6482
								8-v:y
									9-f:4308
							7-v:callableObject
								8-s:GameObject
							7-v:callableFunction
								8-s:GetTransform
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-6546
								8-v:y
									9-f:4542
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:0.1
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-6546
								8-v:y
									9-f:4446
							7-o:constant
								8-v:typeInfo
									9-s:MathVector.float(3)
								8-v:x
									9-i:-4734183927432871936
								8-v:y
									9-i:0
								8-v:z
									9-i:0
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-6822
								8-v:y
									9-f:3863
							7-v:callableObject
								8-s:FluxUtils
							7-v:callableFunction
								8-s:GetActiveFluxComponent
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-6562
								8-v:y
									9-f:3850
							7-v:callableObject
								8-s:FluxComponent
							7-v:callableFunction
								8-s:GetVariable
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-6565
								8-v:y
									9-f:3964
							7-v:callableObject
								8-s:EntityRefDynamic
							7-v:callableFunction
								8-s:GetEntity
					5-k:i
						6-o:d
							7-v:type
								8-s:Cast
							7-v:name
								8-s:GameObject
							7-o:position
								8-v:x
									9-f:-6483
								8-v:y
									9-f:4160
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-6816
								8-v:y
									9-f:3956
							7-o:constant
								8-v:typeInfo
									9-s:String.StringAtom
								8-v:atom
									9-s:HeadBone
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-6105
								8-v:y
									9-f:4564
							7-v:callableObject
								8-s:Transform
							7-v:callableFunction
								8-s:TransformDirection
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-5793
								8-v:y
									9-f:4586
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:MultiplyFVector3Quat
					5-k:i
						6-o:d
							7-v:type
								8-s:Branch
							7-o:position
								8-v:x
									9-f:-8356
								8-v:y
									9-f:2170
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-2658
								8-v:y
									9-f:2788
							7-v:callableObject
								8-s:Input
							7-v:callableFunction
								8-s:IsPlayMode
					5-k:i
						6-o:d
							7-v:type
								8-s:Branch
							7-o:position
								8-v:x
									9-f:-2402
								8-v:y
									9-f:2676
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:1486
								8-v:y
									9-f:3910
							7-v:callableObject
								8-s:Animator
							7-v:callableFunction
								8-s:SetBool
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:1246
								8-v:y
									9-f:4084
							7-o:constant
								8-v:typeInfo
									9-s:String.StringAtom
								8-v:atom
									9-s:Idle
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:990
								8-v:y
									9-f:4202
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:BoolOr
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:1216
								8-v:y
									9-f:4202
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:BoolNot
					5-k:i
						6-o:d
							7-v:type
								8-s:Branch
							7-o:position
								8-v:x
									9-f:156
								8-v:y
									9-f:3908
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:-290
								8-v:y
									9-f:4420
							7-o:constant
								8-v:typeInfo
									9-s:Enum.KeyCode
								8-v:enum
									9-s:Space
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-66
								8-v:y
									9-f:4420
							7-v:callableObject
								8-s:Input
							7-v:callableFunction
								8-s:GetKeyDown
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:428
								8-v:y
									9-f:3828
							7-v:callableObject
								8-s:Animator
							7-v:callableFunction
								8-s:FastForwardState
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:270.131
								8-v:y
									9-f:4129.32
							7-o:constant
								8-v:typeInfo
									9-s:String.StringAtom
								8-v:atom
									9-s:Jump
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:-1091.82
								8-v:y
									9-f:3703.62
							7-v:callableObject
								8-s:CharacterController
							7-v:callableFunction
								8-s:IsGrounded
					5-k:i
						6-o:d
							7-v:type
								8-s:WriteVariable
							7-v:name
								8-s:VerticalVelocity
							7-o:position
								8-v:x
									9-f:670
								8-v:y
									9-f:3828
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:430
								8-v:y
									9-f:3732
							7-o:constant
								8-v:typeInfo
									9-s:Arithmetic.float
								8-v:float
									9-f:5
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:1806
								8-v:y
									9-f:3910
							7-v:callableObject
								8-s:Animator
							7-v:callableFunction
								8-s:SetBool
					5-k:i
						6-o:d
							7-v:type
								8-s:Constant
							7-o:position
								8-v:x
									9-f:1566
								8-v:y
									9-f:4084
							7-o:constant
								8-v:typeInfo
									9-s:String.StringAtom
								8-v:atom
									9-s:Falling
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:1324
								8-v:y
									9-f:3604
							7-v:callableObject
								8-s:MathUtils
							7-v:callableFunction
								8-s:BoolNot
				4-a:links
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:2
							7-v:targetNode
								8-i:3
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:4
							7-v:targetNode
								8-i:5
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:5
							7-v:targetNode
								8-i:3
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:3
							7-v:targetNode
								8-i:1
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:9
							7-v:targetNode
								8-i:8
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:10
							7-v:targetNode
								8-i:9
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:8
							7-v:targetNode
								8-i:12
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:11
							7-v:targetNode
								8-i:13
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:13
							7-v:targetNode
								8-i:12
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:16
							7-v:targetNode
								8-i:20
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:14
							7-v:targetNode
								8-i:16
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:20
							7-v:targetNode
								8-i:15
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:18
							7-v:targetNode
								8-i:17
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:19
							7-v:targetNode
								8-i:17
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:17
							7-v:targetNode
								8-i:15
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:19
							7-v:targetNode
								8-i:13
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:22
							7-v:targetNode
								8-i:24
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:23
							7-v:targetNode
								8-i:21
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:21
							7-v:targetNode
								8-i:24
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:19
							7-v:targetNode
								8-i:21
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:26
							7-v:targetNode
								8-i:25
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:25
							7-v:targetNode
								8-i:22
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:28
							7-v:targetNode
								8-i:29
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:27
							7-v:targetNode
								8-i:30
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:30
							7-v:targetNode
								8-i:29
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:19
							7-v:targetNode
								8-i:30
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:31
							7-v:targetNode
								8-i:32
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:32
							7-v:targetNode
								8-i:28
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:34
							7-v:targetNode
								8-i:33
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:1
							7-v:targetNode
								8-i:6
							7-v:sourcePin
								8-i:2
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:7
							7-v:targetNode
								8-i:6
							7-v:targetPin
								8-i:3
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:40
							7-v:targetNode
								8-i:39
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:39
							7-v:targetNode
								8-i:38
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:43
							7-v:targetNode
								8-i:41
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:43
							7-v:targetNode
								8-i:41
							7-v:targetPin
								8-i:4
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:42
							7-v:targetNode
								8-i:44
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:44
							7-v:targetNode
								8-i:41
							7-v:targetPin
								8-i:3
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:45
							7-v:targetNode
								8-i:44
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:46
							7-v:targetNode
								8-i:8
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:35
							7-v:targetNode
								8-i:46
							7-v:sourcePin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:46
							7-v:targetNode
								8-i:20
							7-v:sourcePin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:46
							7-v:targetNode
								8-i:22
							7-v:sourcePin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:46
							7-v:targetNode
								8-i:28
							7-v:sourcePin
								8-i:3
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:38
							7-v:targetNode
								8-i:48
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:47
							7-v:targetNode
								8-i:6
							7-v:targetPin
								8-i:4
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:48
							7-v:targetNode
								8-i:49
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:47
							7-v:targetNode
								8-i:50
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:50
							7-v:targetNode
								8-i:49
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:36
							7-v:targetNode
								8-i:38
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:49
							7-v:targetNode
								8-i:52
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:52
							7-v:targetNode
								8-i:51
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:53
							7-v:targetNode
								8-i:51
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:49
							7-v:targetNode
								8-i:53
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:51
							7-v:targetNode
								8-i:6
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:6
							7-v:targetNode
								8-i:56
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:55
							7-v:targetNode
								8-i:57
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:6
							7-v:targetNode
								8-i:57
							7-v:sourcePin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:56
							7-v:targetNode
								8-i:58
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:59
							7-v:targetNode
								8-i:58
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:60
							7-v:targetNode
								8-i:62
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:62
							7-v:targetNode
								8-i:61
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:63
							7-v:targetNode
								8-i:61
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:56
							7-v:targetNode
								8-i:64
							7-v:sourcePin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:61
							7-v:targetNode
								8-i:64
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:54
							7-v:targetNode
								8-i:65
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:65
							7-v:targetNode
								8-i:51
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:70
							7-v:targetNode
								8-i:69
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:69
							7-v:targetNode
								8-i:71
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:71
							7-v:targetNode
								8-i:68
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:68
							7-v:targetNode
								8-i:74
							7-v:sourcePin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:74
							7-v:targetNode
								8-i:73
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:76
							7-v:targetNode
								8-i:75
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:72
							7-v:targetNode
								8-i:75
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:43
							7-v:targetNode
								8-i:73
							7-v:targetPin
								8-i:4
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:79
							7-v:targetNode
								8-i:78
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:77
							7-v:targetNode
								8-i:78
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:80
							7-v:targetNode
								8-i:79
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:77
							7-v:targetNode
								8-i:79
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:41
							7-v:targetNode
								8-i:81
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:81
							7-v:targetNode
								8-i:73
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:78
							7-v:targetNode
								8-i:81
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:82
							7-v:targetNode
								8-i:83
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:75
							7-v:targetNode
								8-i:83
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:83
							7-v:targetNode
								8-i:78
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:78
							7-v:targetNode
								8-i:73
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:43
							7-v:targetNode
								8-i:73
							7-v:targetPin
								8-i:3
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:84
							7-v:targetNode
								8-i:85
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:66
							7-v:targetNode
								8-i:88
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:87
							7-v:targetNode
								8-i:88
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:88
							7-v:targetNode
								8-i:50
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:85
							7-v:targetNode
								8-i:88
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:86
							7-v:targetNode
								8-i:66
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:67
							7-v:targetNode
								8-i:87
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:68
							7-v:targetNode
								8-i:41
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:89
							7-v:targetNode
								8-i:90
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:91
							7-v:targetNode
								8-i:90
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:90
							7-v:targetNode
								8-i:92
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:93
							7-v:targetNode
								8-i:94
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:96
							7-v:targetNode
								8-i:95
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:92
							7-v:targetNode
								8-i:95
							7-v:targetPin
								8-i:3
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:95
							7-v:targetNode
								8-i:97
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:98
							7-v:targetNode
								8-i:97
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:90
							7-v:targetNode
								8-i:99
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:100
							7-v:targetNode
								8-i:99
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:99
							7-v:targetNode
								8-i:97
							7-v:targetPin
								8-i:3
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:101
							7-v:targetNode
								8-i:102
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:94
							7-v:targetNode
								8-i:101
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:102
							7-v:targetNode
								8-i:95
							7-v:sourcePin
								8-i:2
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:102
							7-v:targetNode
								8-i:97
							7-v:sourcePin
								8-i:2
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:49
							7-v:targetNode
								8-i:89
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:103
							7-v:targetNode
								8-i:69
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:104
							7-v:targetNode
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:105
							7-v:targetNode
								8-i:94
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:106
							7-v:targetNode
								8-i:40
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:107
							7-v:targetNode
								8-i:66
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:107
							7-v:targetNode
								8-i:87
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:109
							7-v:targetNode
								8-i:110
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:108
							7-v:targetNode
								8-i:109
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:110
							7-v:targetNode
								8-i:41
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:35
							7-v:targetNode
								8-i:1
							7-v:sourcePin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:115
							7-v:targetNode
								8-i:114
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:112
							7-v:targetNode
								8-i:113
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:114
							7-v:targetNode
								8-i:112
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:111
							7-v:targetNode
								8-i:114
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:113
							7-v:targetNode
								8-i:117
							7-v:sourcePin
								8-i:2
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:113
							7-v:targetNode
								8-i:117
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:116
							7-v:targetNode
								8-i:118
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:118
							7-v:targetNode
								8-i:117
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:120
							7-v:targetNode
								8-i:119
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:119
							7-v:targetNode
								8-i:92
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:119
							7-v:targetNode
								8-i:100
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:121
							7-v:targetNode
								8-i:62
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:37
							7-v:targetNode
								8-i:42
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:37
							7-v:targetNode
								8-i:72
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:125
							7-v:targetNode
								8-i:126
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:127
							7-v:targetNode
								8-i:126
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:126
							7-v:targetNode
								8-i:124
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:127
							7-v:targetNode
								8-i:124
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:123
							7-v:targetNode
								8-i:126
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:128
							7-v:targetNode
								8-i:65
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:16
							7-v:targetNode
								8-i:131
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:32
							7-v:targetNode
								8-i:134
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:135
							7-v:targetNode
								8-i:134
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:136
							7-v:targetNode
								8-i:134
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:134
							7-v:targetNode
								8-i:130
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:29
							7-v:targetNode
								8-i:137
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:25
							7-v:targetNode
								8-i:138
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:32
							7-v:targetNode
								8-i:138
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:131
							7-v:targetNode
								8-i:130
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:132
							7-v:targetNode
								8-i:139
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:133
							7-v:targetNode
								8-i:139
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:139
							7-v:targetNode
								8-i:131
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:136
							7-v:targetNode
								8-i:140
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:139
							7-v:targetNode
								8-i:140
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:140
							7-v:targetNode
								8-i:131
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:142
							7-v:targetNode
								8-i:141
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:137
							7-v:targetNode
								8-i:129
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:130
							7-v:targetNode
								8-i:129
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:137
							7-v:targetNode
								8-i:141
							7-v:sourcePin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:147
							7-v:targetNode
								8-i:146
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:143
							7-v:targetNode
								8-i:145
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:146
							7-v:targetNode
								8-i:143
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:144
							7-v:targetNode
								8-i:146
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:123
							7-v:targetNode
								8-i:68
							7-v:sourcePin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:123
							7-v:targetNode
								8-i:145
							7-v:sourcePin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:145
							7-v:targetNode
								8-i:148
							7-v:sourcePin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:148
							7-v:targetNode
								8-i:150
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:150
							7-v:targetNode
								8-i:151
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:152
							7-v:targetNode
								8-i:151
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:153
							7-v:targetNode
								8-i:152
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:153
							7-v:targetNode
								8-i:152
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:154
							7-v:targetNode
								8-i:152
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:145
							7-v:targetNode
								8-i:155
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:148
							7-v:targetNode
								8-i:155
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:151
							7-v:targetNode
								8-i:155
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:149
							7-v:targetNode
								8-i:156
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:156
							7-v:targetNode
								8-i:151
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:157
							7-v:targetNode
								8-i:156
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:28
							7-v:targetNode
								8-i:137
							7-v:sourcePin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:138
							7-v:targetNode
								8-i:137
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:9
							7-v:targetNode
								8-i:158
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:16
							7-v:targetNode
								8-i:158
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:158
							7-v:targetNode
								8-i:139
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:122
							7-v:targetNode
								8-i:113
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:160
							7-v:targetNode
								8-i:159
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:160
							7-v:targetNode
								8-i:159
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:161
							7-v:targetNode
								8-i:159
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:159
							7-v:targetNode
								8-i:162
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:74
							7-v:targetNode
								8-i:163
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:164
							7-v:targetNode
								8-i:163
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:165
							7-v:targetNode
								8-i:163
							7-v:targetPin
								8-i:4
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:171
							7-v:targetNode
								8-i:168
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:169
							7-v:targetNode
								8-i:170
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:168
							7-v:targetNode
								8-i:169
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:167
							7-v:targetNode
								8-i:168
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:170
							7-v:targetNode
								8-i:164
							7-v:sourcePin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:73
							7-v:targetNode
								8-i:170
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:170
							7-v:targetNode
								8-i:163
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:164
							7-v:targetNode
								8-i:172
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:166
							7-v:targetNode
								8-i:172
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:172
							7-v:targetNode
								8-i:173
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:162
							7-v:targetNode
								8-i:173
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:173
							7-v:targetNode
								8-i:163
							7-v:targetPin
								8-i:3
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:117
							7-v:targetNode
								8-i:174
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:174
							7-v:targetNode
								8-i:123
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:116
							7-v:targetNode
								8-i:174
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:35
							7-v:targetNode
								8-i:33
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:176
							7-v:targetNode
								8-i:35
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:175
							7-v:targetNode
								8-i:176
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:targetNode
								8-i:176
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:97
							7-v:targetNode
								8-i:177
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:102
							7-v:targetNode
								8-i:177
							7-v:sourcePin
								8-i:2
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:178
							7-v:targetNode
								8-i:177
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:92
							7-v:targetNode
								8-i:179
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:99
							7-v:targetNode
								8-i:179
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:180
							7-v:targetNode
								8-i:177
							7-v:targetPin
								8-i:3
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:179
							7-v:targetNode
								8-i:180
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:58
							7-v:targetNode
								8-i:181
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:182
							7-v:targetNode
								8-i:183
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:183
							7-v:targetNode
								8-i:181
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:181
							7-v:targetNode
								8-i:184
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:64
							7-v:targetNode
								8-i:95
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:181
							7-v:targetNode
								8-i:95
							7-v:sourcePin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:102
							7-v:targetNode
								8-i:184
							7-v:sourcePin
								8-i:2
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:185
							7-v:targetNode
								8-i:184
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:102
							7-v:targetNode
								8-i:6
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:1
							7-v:targetNode
								8-i:102
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:176
							7-v:targetNode
								8-i:35
							7-v:sourcePin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:186
							7-v:targetNode
								8-i:56
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:1
							7-v:targetNode
								8-i:186
							7-v:sourcePin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:184
							7-v:targetNode
								8-i:187
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:187
							7-v:targetNode
								8-i:95
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:188
							7-v:targetNode
								8-i:187
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:190
							7-v:targetNode
								8-i:189
							7-v:targetPin
								8-i:2
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:177
							7-v:targetNode
								8-i:189
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:102
							7-v:targetNode
								8-i:189
							7-v:sourcePin
								8-i:2
							7-v:targetPin
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:186
							7-v:targetNode
								8-i:191
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:191
							7-v:targetNode
								8-i:189
							7-v:targetPin
								8-i:3
				4-a:variables
					5-k:item
						6-v:first
							7-s:VerticalVelocity
						6-o:second
							7-v:typeInfo
								8-s:Arithmetic.float
							7-v:float
								8-f:0
					5-k:item
						6-v:first
							7-s:CameraPitch
						6-o:second
							7-v:typeInfo
								8-s:Arithmetic.float
							7-v:float
								8-f:0
					5-k:item
						6-v:first
							7-s:BodyYawTarget
						6-o:second
							7-v:typeInfo
								8-s:Arithmetic.float
							7-v:float
								8-f:0
					5-k:item
						6-v:first
							7-s:CursorLock
						6-o:second
							7-v:typeInfo
								8-s:Object.CursorLock
					5-k:item
						6-v:first
							7-s:Direction
						6-o:second
							7-v:typeInfo
								8-s:MathVector.float(3)
							7-v:x
								8-i:0
							7-v:y
								8-i:0
							7-v:z
								8-i:0
