sra format
use tabs: true
0-r:Root
	1-o:asset
		2-v:type
			3-s:FluxGraphAsset
		2-o:ptr
			3-o:graph
				4-a:nodes
					5-k:i
						6-o:d
							7-v:type
								8-s:Event
							7-v:name
								8-s:Update
							7-o:position
								8-v:x
									9-f:-322
								8-v:y
									9-f:68
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:62
								8-v:y
									9-f:68
							7-v:callableObject
								8-s:RayCast3D
							7-v:callableFunction
								8-s:CastSingle
					5-k:i
						6-o:d
							7-v:type
								8-s:Invoke
							7-o:position
								8-v:x
									9-f:682
								8-v:y
									9-f:68
							7-v:callableObject
								8-s:DebugOverlayDraw
							7-v:callableFunction
								8-s:DrawSphere
					5-k:i
						6-o:d
							7-v:type
								8-s:Branch
							7-o:position
								8-v:x
									9-f:396
								8-v:y
									9-f:68
					5-k:i
						6-o:d
							7-v:type
								8-s:Evaluate
							7-o:position
								8-v:x
									9-f:286
								8-v:y
									9-f:276
							7-v:callableObject
								8-s:FluxUtils
				4-a:links
					5-k:i
						6-o:d
							7-v:targetNode
								8-i:1
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:1
							7-v:targetNode
								8-i:3
					5-k:i
						6-o:d
							7-v:sourceNode
								8-i:3
							7-v:targetNode
								8-i:2
				4-a:variables
